services:
  db:
    image: postgres:16
    container_name: fastfood-pagamento-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - fastfood-pagamento-db:/var/lib/postgresql/data
    networks:
      - fastfood-pagamento-net

  app:
    build: .
    container_name: fastfood-pagamento-app
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "5005:5005"
    command: >
      java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
           -jar app.jar
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - fastfood-pagamento-net
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"

  # --------------------------------------------------------
  # Zookeeper (necessário para Kafka)
  # --------------------------------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - fastfood-pagamento-net
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

  # --------------------------------------------------------
  # Kafka (mensageria entre microserviços)
  # --------------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - fastfood-pagamento-net

# --------------------------------------------------------
# VOLUMES DEFINITION
# --------------------------------------------------------
volumes:
  fastfood-pagamento-db:
  zookeeper-data:      # Added this
  zookeeper-log: # Added this

networks:
  fastfood-pagamento-net: